# Generated by Django 3.2 on 2022-10-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faction_fleet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='owner',
            new_name='faction',
        ),
    ]
