# Generated by Django 3.2 on 2022-10-04 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.OneToOneField(default='b5ae0e61-5658-4987-b964-49c96eff50f2', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='fleet',
            field=models.OneToOneField(default='b5ae0e61-5658-4987-b964-49c96eff50f2', on_delete=django.db.models.deletion.CASCADE, related_name='project', to='core.fleet'),
            preserve_default=False,
        ),
    ]
