# Generated by Django 3.2 on 2022-10-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221004_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.TextField(null=True),
        ),
    ]
