# Generated by Django 3.2 on 2022-10-05 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_project_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='faction',
            field=models.ForeignKey(default='510d1d19-c170-488b-844f-ec7d2404c72f', on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='core.faction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colony',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='core.body'),
        ),
    ]
