# Generated by Django 3.2 on 2022-10-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221006_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignedFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_key', models.CharField(max_length=50)),
                ('fleet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned_fleets', to='core.fleet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assigned_fleets', to='core.project')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectFleet',
        ),
    ]
