# Generated by Django 3.2 on 2022-10-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20221006_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key',
            field=models.CharField(default='construct_colony', max_length=50),
            preserve_default=False,
        ),
    ]
