# Generated by Django 3.2 on 2022-10-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_project_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.body'),
        ),
    ]
