# Generated by Django 3.2 on 2021-04-20 21:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GalaxyData',
            fields=[
                ('key', models.CharField(editable=False, max_length=200, primary_key=True, serialize=False)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='galaxy.colony')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='galaxy.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StellarBody',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('body_type', models.CharField(max_length=200)),
                ('position_x', models.IntegerField()),
                ('position_y', models.IntegerField()),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stellar_bodies', to='galaxy.system')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceStockpile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_stockpile', to='galaxy.holding')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.resource')),
                ('stellar_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_deposits', to='galaxy.stellarbody')),
            ],
        ),
        migrations.CreateModel(
            name='Hyperlane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.system')),
                ('system2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.system')),
            ],
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleets', to='galaxy.faction')),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='galaxy.colony')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.species')),
            ],
        ),
        migrations.AddField(
            model_name='colony',
            name='stellar_body',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonies', to='galaxy.stellarbody'),
        ),
    ]
