# Generated by Django 3.2 on 2021-04-21 22:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.buildingtype')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='galaxy.holding')),
            ],
        ),
        migrations.RenameField(
            model_name='resourcedeposit',
            old_name='count',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='resourcestockpile',
            old_name='count',
            new_name='amount',
        ),
        migrations.CreateModel(
            name='ConstructionProjectAllocatedResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_resources', to='galaxy.constructionproject')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.resource')),
            ],
        ),
    ]
