# Generated by Django 3.2 on 2021-04-21 23:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_auto_20210421_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuidingTypeRequiredResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField()),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_resources', to='galaxy.buildingtype')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.resource')),
            ],
        ),
    ]
