# Generated by Django 3.2 on 2021-04-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0003_buidingtyperequiredresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='required_progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='constructionprojectallocatedresource',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
