# Generated by Django 3.2 on 2021-04-21 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0004_auto_20210421_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='galaxy.buildingtype')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='galaxy.holding')),
            ],
        ),
    ]
