# Generated by Django 3.2 on 2021-04-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0005_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buidingtyperequiredresource',
            old_name='construction_project',
            new_name='building_type',
        ),
    ]
