# Generated by Django 3.2 on 2021-04-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0006_rename_construction_project_buidingtyperequiredresource_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='name',
            field=models.CharField(default='Factory', max_length=200),
            preserve_default=False,
        ),
    ]
