# Generated by Django 3.2 on 2021-04-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0007_buildingtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
