# Generated by Django 3.2 on 2021-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0008_alter_resource_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestockpile',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
