# Generated by Django 3.2 on 2021-04-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0009_alter_resourcestockpile_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestockpile',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_stockpiles', to='galaxy.holding'),
        ),
    ]
