# Generated by Django 3.2 on 2021-04-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0011_alter_resourcedeposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcestockpile',
            name='amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
