# Generated by Django 3.2 on 2021-05-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0012_alter_resourcestockpile_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
