# Generated by Django 3.2 on 2021-05-12 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0013_building_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipConstructionProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ship_type', models.CharField(max_length=200)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ship_construction_projects', to='galaxy.holding')),
            ],
        ),
    ]
